[project]
name = "ygtb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "commentjson>=0.9.0",
    "crewai[tools]>=1.7.1",
    "duckduckgo-search>=8.1.1",
    "langchain-community>=0.3.5",
    "langchain-openai>=0.3.23",
    "moviepy==1.0.3",
    "orjson>=3.11.4",
    "selenium>=4.38.0",
    "termcolor>=3.2.0",
    "webdriver-manager>=4.0.2",
    "yfinance>=0.2.66",
]

[tool.ruff]
# lint.extend-select = []
# lint.ignore = ["F401"]